### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [The-Realm-18-Studios/Beyond-Planets-Dimensions#1]
### Mod loader

Forge

### Minecraft version

1.18.2

### Beyond Planets - Dimensions version

Beyond-Planets-Dimensions-1.18.2-1.0.5.jar

### Modloader version

40.1.25

### Modpack info

my own modpack

### The latest.log file

https://pastebin.com/P2SnPnuL

### Issue description

Crash at startup

### Other information

crashlog

https://pastebin.com/mYBAyPRV

**Comment by TheRealM18** [comment]
Have you tried without optifine.  Optifine do not work with beyond earth, and most mod authors will not support people that use optifine.

Optifine is a very intrusive mod, that breaks a lot of stuff. Including making servers easier to use hacks because of the math they use.

If you remove optifine, and try again, that would be my first try, as its an optifine error happening.

**Comment by agentwolf88** [comment]
Optifine works fine with beyond earth for me. The problem is not optifine. Here is a crashlog without optifine
[crash-2022-05-27_14.47.16-fml.txt](https://github.com/The-Realm-18-Studios/Beyond-Planets-Dimensions/files/8786744/crash-2022-05-27_14.47.16-fml.txt)
.

**Comment by TheRealM18** [comment]
Well Optifine is not installed, you are not running the correct version of Beyond Earth.  The version of Beyond Earth that is needed, is not on curseforge yet.  If it is the correct version, Beyond Earth: Giselle Addon will not work.  There are massive changes in the planet API, you need to understand that we are running the mod ready for upcoming builds,  not current.

**Comment by agentwolf88** [comment]
i use this version 

https://github.com/TathanDev/StarWarsPlanets/blob/main/libs/net/mrscauthd/beyond_earth/1.18.2-6.0/beyond-earth-1.18.2-6.0.jar

Dev 6.2

**Comment by TheRealM18** [comment]
The version then will not work with Beyond Earth: Giselle Addon. Either remove that one, or Removed the dimensions.  I said this in pervious message, they will not work together right now.  This is a known issue, and there is nothing I can do to solve it.
